#!/usr/bin/env sh

tmux kill-session -t plutus
tmux new -s plutus -d

tmux split-window -vb
tmux split-window -h
tmux split-window -vb
tmux split-window -v

tmux send-keys -t plutus.1 'cd plutus-playground-client' Enter
tmux send-keys -t plutus.1 'plutus-playground-server' Enter

tmux send-keys -t plutus.0 'cd plutus-playground-client' Enter
tmux send-keys -t plutus.0 'npm run start' Enter

tmux send-keys -t plutus.3 'cat /vcw/pwd/urls.txt' Enter

tmux send-keys -t plutus.4 'cd /plutus/plutus' Enter
tmux send-keys -t plutus.4 'nix build -f default.nix docs.site' Enter
tmux send-keys -t plutus.4 "tmux send-keys -t plutus.2 'cd /vcw/pwd/haddock-web' Enter" Enter
tmux send-keys -t plutus.4 "tmux send-keys -t plutus.2 './plutus-haddock -s /plutus/plutus/result' Enter" Enter
tmux send-keys -t plutus.4 "clear" Enter
tmux send-keys -t plutus.4 "#-----------------------------------" Enter

if [[ "$@" != "" ]] ; then
  tmux send-keys -t plutus.4 "cd /plutus/$1" Enter
  tmux send-keys -t plutus.4 "cabal update" Enter
  tmux send-keys -t plutus.4 "cabal repl" Enter
fi
tmux select-pane -t plutus.4

tmux attach -t plutus
