#!/usr/bin/env sh

# sh argument should exit the script
if [[ "$(echo "$1")" == "$(echo "sh")" ]] ; then sh; exit; fi
echo ""

# --help argument prints help information
if [[ "$(echo "$1")" == "$(echo "--extract")" ]] ; then echo "Extracting the mangement scripts ..."; echo""; cp /vcw/pwd/scripts/* /plutus; find /plutus/* -type f  -maxdepth 1 -exec chmod 755 -- {} +; exit; fi

#---------------------------------------------------------------------------------------------------------------------------------

# Print the header welcome message
cat /vcw/pwd/welcome.txt;
cat /vcw/pwd/urls.txt;

# --help argument prints help information - or if the plutus folder hasn't been mapped in the echo docker run command
if [[ "$(echo "$1")" == "$(echo "--help")" || ! -d /plutus || "$(df -h | grep /nix)" == "" ]] ; then cat /vcw/pwd/help.txt; exit; fi

#---------------------------------------------------------------------------------------------------------------------------------

# block main thread of container
tail -f
