#!/usr/bin/env sh

# sh argument should exit the script
if [[ "$(echo "$1")" == "$(echo "sh")" ]] ; then sh; exit; fi
echo ""

# --help argument prints help information
if [[ "$(echo "$1")" == "$(echo "--extract")" ]] ; then echo "Extracting the mangement scripts ..."; echo""; cp /vcw/pwd/scripts/* /plutus; find /plutus/* -type f  -maxdepth 1 -exec chmod 755 -- {} +; exit; fi

#---------------------------------------------------------------------------------------------------------------------------------

# Print the header welcome message
cat /vcw/pwd/welcome.txt;

# if the plutus folder hasn't been mapped in the echo docker run command
if [[ ! -d /plutus || "$(df -h | grep /nix)" == "" ]] ; then cat /vcw/pwd/management.txt; exit; fi

cat /vcw/pwd/urls.txt;

# --help argument prints help information
if [[ "$(echo "$1")" == "$(echo "--help")" ]] ; then cat /vcw/pwd/help.txt; exit; fi

#---------------------------------------------------------------------------------------------------------------------------------

# Install prerequisites
if [[ "$(which git)" == "" ]] ; then echo "installing git ..."; nix-env --install git; else echo "git is already installed ..."; fi
if [[ "$(which tmux)" == "" ]] ; then echo "installing tmux ..."; nix-env --install tmux; else echo "tmux is already installed ..."; fi

tmux new -s plutus -d
tmux send-keys -t plutus.0 '/vcw/pwd/prepare-playground' Enter
tail -f
